name: "Hello World"
description: "Greet someone"
inputs:
  config-path: # id of input
    description: "Path to the config file"
    required: true
    default: "./mt_config.json"
outputs:
  test:
    description: "test"
    value: "test"
runs:
  using: "composite"
  steps:
    - run: echo Running MT diagrams on the config ${{ inputs.config-path }}.
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mt-diagrams
      shell: bash

    - name: Run MT diagrams
      run: |
        mt-diagrams render --config-path ${{ inputs.config-path }}
      shell: bash

    - uses: mshick/add-pr-comment@v2
      with:
        message: |
          ![zeeguu-completeViewdiffView](https://user-images.githubusercontent.com/33089800/221556907-5baa568c-b3bc-4a8d-b698-d52cdf0897ba.png)

    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
