name: "Upload MT diagram to PR"
description: "This will create and upload mt diagrams to a PR"
inputs:
  config-path:
    description: "Path to the config file"
    required: true
    default: "mt_config.json"
  imgur-secret-id:
    description: "The imgur secret key"
    required: true
  render-diff:
    description: "Should it render diff"
    required: true
    default: "false"

runs:
  using: "composite"
  steps:
    - run: echo Running MT diagrams on the config ${{ inputs.config-path }}.
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mt-diagrams
      shell: bash

    - name: Run MT diagrams
      run: |
        if [ "${{inputs.render-diff}}" == "true" ] 
        then
          mt-diagrams render-diff --config-path ${{ inputs.config-path }}
        else
          mt-diagrams render --config-path ${{ inputs.config-path }}
        fi
        cd diagrams && ls -la && cd ..
      shell: bash

    # - uses: devicons/public-upload-to-imgur@v2.2.2
    #   name: Upload to imgur
    #   id: imgur_step
    #   with:
    #     path: |
    #       diagrams/*.png
    #     client_id: ${{ inputs.imgur-secret-id }}

    - name: Upload to imgur proxy
      id: imgur_proxy
      run: |
        results=()
        for file in diagrams/*.png; do
          result=$(curl -s -X POST -F "image=@$file" https://imgurproxy-app-service.azurewebsites.net/upload)
          results+=("$result")
        done
        echo $result
        res=[$(echo $result | sed 's/ /, /g')]
        echo $res
        echo "MARKDOWN=$res" >> $GITHUB_OUTPUT
      shell: bash

    - uses: mshick/add-pr-comment@v2
      with:
        message: |
          ${{ fromJSON(steps.imgur_proxy.outputs.markdown)[0] }}
          ${{ fromJSON(steps.imgur_proxy.outputs.markdown)[1] }}

    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
