name: Test MT action

on:
  - pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - id: mt-diagrams
        uses: Perlten/mt-gh-action@test
        with:
          config-path: "./test_project/mt_config.json"

      - run: echo mt output ${{ steps.mt-diagrams.outputs.test }}
        shell: bash
