name: Test MT action

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: foo
        uses: ./../../action.yml
        with:
          who-to-greet: "Mona the Octocat"

      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
